name: todyapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  auto_route: ^7.7.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  flutter_config: ^2.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  awesome_snackbar_content: ^0.1.3
  flutter_easyloading: ^3.0.5

  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  app_links: ^3.4.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:
  auto_route_generator: ^7.2.0
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Sf-pro-display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
